### ISSUE TITLE
你好

### ISSUE THREAD

**Issue by hotmop** [546669204/vps-inventory-monitoring#1]
请问有没有教程呢？直接git代码到空间就可以访问了吗？有没有联系方式

**Comment by 546669204** [comment]
1.导入数据库文件 data.sql
2.修改数据库配置文件 \vps-inventory-monitoring\app\database.php
3.设置 \vps-inventory-monitoring\public 为网站运行目录
4.即可正常使用
如果还有问题可以联系我的QQ 546669204
