### ISSUE TITLE
POST 请求如何实现?

### ISSUE THREAD

**Issue by nickfox-taterli** [546669204/vps-inventory-monitoring#10]
比如这个产品,需要POST数据到https://www.umaxhosting.com/manage/cart.php完成查询.

POST内容:ajax=1&a=confproduct&calctotal=true&configure=true&i=0&billingcycle=monthly&hostname=&rootpw=f61adc8e4a&ns1prefix=ns1&ns2prefix=ns2&configoption%5B1%5D=11&configoption%5B2%5D=2

套餐名:

256MB LEB VPS

256MB DDR3 RAM
256MB vSwap
50GB RAID-10 Storage
2000GB Monthly Bandwidth
100Mbps Network Port
SolusVM Control Panel
Unlimited OS Reinstalls
Full Root Privileges
Instant Deployment
Easy API Access

**Comment by 546669204** [comment]
```
   $curl = go_curl($value["vurl"],"post",["ajax"=>1,"a"=>"confproduct","calctotal"=>true]);//类似于这样就可以以post 的方式访问
   $str = $curl["Body"];
下面一样是验证
```
验证函数可以重写成如上
