### ISSUE TITLE
页面错误！请稍后再试～

### ISSUE THREAD

**Issue by Blake-Bill** [546669204/vps-inventory-monitoring#11]
所有项目都做好了，开启以后就提示这个，index开了debug无错误信息输出。
环境：nginx1.14+php7.2+mariadb10.2

**Comment by 546669204** [comment]
这个是缺少了验证码的库。我刚刚修复了下载新的文件。
https://github.com/546669204/vps-inventory-monitoring/tree/f09a9fd433de6262ff05e5451017122e838dee2a
