### ISSUE TITLE
网页打开提示”页面错误！请稍后再试～“

### ISSUE THREAD

**Issue by bobscyes** [546669204/vps-inventory-monitoring#15]
在/www/wwwlogs/vps.domain.net.error.log的报错：

2019/02/18 04:02:00 [error] 22233#0: *450 FastCGI sent in stderr: "PHP message: PHP Warning:  require(): open_basedir restriction in effect. File(/www/wwwroot/vps.domain.net/thinkphp/start.php) is not within the allowed path(s): (/www/wwwroot/vps.domain.net/public/:/tmp/:/proc/) in /www/wwwroot/vps.domain.net/public/index.php on line 17

PHP message: PHP Warning:  require(/www/wwwroot/vps.domain.net/thinkphp/start.php): failed to open stream: Operation not permitted in /www/wwwroot/vps.domain.net/public/index.php on line 17

PHP message: PHP Fatal error:  require(): Failed opening required '/www/wwwroot/vps.domain.net/public/../thinkphp/start.php' (include_path='.:/www/server/php/71/lib/php') in /www/wwwroot/vps.domain.net/public/index.php on line 17" while reading response header from upstream, client: 98.14.182.114, server: vps.yuecloud.net, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/tmp/php-cgi-71.sock:", host: "vps.yuecloud.net"

好像是我有什么地方没有配置正确，感觉是open_basedir目录没有改正确，应该是网站根目录，不是public吧？我也修改了.user.ini文件里的路径，还是不行，在nginx.conf也加了路径，也还是报错

**Comment by 546669204** [comment]
修改open_basedir   "/www/wwwroot/vps.domain.net/public/:/tmp/:/proc/"
为 "/www/wwwroot/vps.domain.net/:/tmp/:/proc/"

**Comment by bobscyes** [comment]
谢谢解答，我已经把.user.ini里面的open_basedir改为/www/wwwroot/vps.domain.net/:/tmp/:/proc/

我也试一下grep -r "open_basedir=/www/wwwroot/vps.domian.net/public/" /www
都没有找到结果，不知道为啥这个错误信息里还有public

我也觉得应该是open_basedir没设置好，但是不知道错在哪里

我是用得宝塔，Nginx-1.15，PHP-5.4，MySQL-5.5

**Comment by 546669204** [comment]
修改配置有重启吗
