### ISSUE TITLE
添加 https://t.me/VpsStockBot 获取 sckey 的问题

### ISSUE THREAD

**Issue by ttydy** [546669204/vps-inventory-monitoring#16]
在频道中已经加了https://t.me/VpsStockBot为管理员，发送/star 一直获取不到sckey是什么问题？

**Comment by 546669204** [comment]
可以看一下这个项目 https://github.com/546669204/Telegram-Push-Bot
自己搭建tg机器人

**Comment by ttydy** [comment]
VpsStockBot是停用了吗？也是用这个搭的？非常感觉你的回答。

**Comment by ttydy** [comment]
> 可以看一下这个项目 https://github.com/546669204/Telegram-Push-Bot
> 自己搭建tg机器人

VpsStockBot是停用了吗？也是用这个搭的？非常感觉你的回答。

**Comment by 546669204** [comment]
是的。我把那个机器人关掉了。

**Comment by ttydy** [comment]
感谢，我去试着搭一下。

**Comment by ttydy** [comment]
你好，有这么个问题。比如一个商品没有货，我在测试的时候把false改为true。运行 php think VpsTest 后显示有货了。但是频道没有收到信息。请问这是什么问题？

用下面这个测试过是可以收到信息的。
Send a message POST http://[domain]/bot.php

method=send&sckey=[XXX]&content=[CONTENT]

**Comment by ttydy** [comment]
忽略，已经搞好了。

**Comment by aff2018** [comment]
我建了一个bot，也添加到群组，并给了管理员权限，在群组中发生/start,没有任何返回值？

**Comment by 546669204** [comment]
设置了webhook吗 tg机器人的 然后检查一下是不是 https

**Comment by aff2018** [comment]
嗯，解决了，多复制了点内容。谢谢🙏

546669204 <notifications@github.com>于2019年6月25日 周二09:33写道：

**Comment by 546669204** [comment]
好的。
