### ISSUE TITLE
安装你提供的方法，网页端补货，搭建成功了，怎么搞tg bot通知呢？

### ISSUE THREAD

**Issue by aff2018** [546669204/vps-inventory-monitoring#17]
1.网页端补货已成功搭建
2.https://github.com/546669204/Telegram-Push-Bot
按这机器人办法也设置好：
修改bot.php文件：
function sendmessage($data){
go_curl("https://api.telegram.org/bot[token]/sendMessage","POST",$data);
}
把[token]换成了我的机器人token
并把bot.php放在了网站public目录 下了
运行：
https://api.telegram.org/bot[Token]/setWebhook?url=https://[domain]/bot.php
[token],[domain]换成我自己的设置了，也返回成功的提示了。
这句运行没反应：https://[domain]/bot.php
method=send&sckey=[XXX]&content=[CONTENT]
bot.php和method之间没有连接符“?”吗？
3.现在，在网页端程序里需要怎么配置？

**Comment by 546669204** [comment]
https://[domain]/bot.php
method=send&sckey=[XXX]&content=[CONTENT]
这是一个post 请求 
第一行为url
第二行为body 
成功之后 和 机器人聊天 会返回 sckey  使用 sckey 调用 bot 这个请求 就可以测试 发送消息

**Comment by aff2018** [comment]
https://[domain]/bot.php
method=send&sckey=[XXX]&content=[CONTENT]

这个是在浏览器里运行吧？复制进浏览器，回车，没有任何反应！？


在网页端程序里还需要怎么配置吗？

**Comment by 546669204** [comment]
post 请求 模拟 
网页端 不用特殊 配置

**Comment by aff2018** [comment]
不理解这一句要在哪里运行呢？我是菜菜，不懂就问，别嫌弃，233！
https://[domain]/bot.php
method=send&sckey=[XXX]&content=[CONTENT]

**Comment by 546669204** [comment]
使用过postman 这类软件吗  模拟发送请求的  

http://www.jsons.cn/httpurl/ 或者使用这个 测试

**Comment by aff2018** [comment]
谢谢，总算明白这个意思了，原来有这些工具进行调试的。

这个文件中：
https://github.com/546669204/vps-inventory-monitoring/blob/master/gotest/config.json
{
    "mysqlname":"vps",
    "mysqluser":"",
    "mysqlpass":"",
    "mysqlhost":"127.0.0.1",
    "mysqlport":3306,
    "ThreadNumber":100,
    "VerifyType":1,
    "title":"您关注的{{.name}}有货啦。",
    "content":"您关注的{{.name}}有货啦。\n快来大肆抢购呀。\n测评地址：$host/ceping/{{.id}}\n购买地址：$host/buy/{{.id}}",
    "tgchannelsckey":"",
    "tgboturl":"https://cloud.hcaiyue.top/tgbot.php",
    "proxy":["local"]
}
网站程序，这里不用改成我自己的数据库用户名什么的吗？

**Comment by 546669204** [comment]
需要的 之前 这边 没有修改吗

**Comment by aff2018** [comment]
修改了的。
你之前不是说网站程序不用改动嘛，于是问一下要不要改。

**Comment by 546669204** [comment]
数据库配置还是要改的。

**Comment by aff2018** [comment]
php /路径/域名/think VpsTest

我五分钟跑一个，两天来，发现vps死了两次。

这个补货程序，对vps配置有要求不？
我的Do 1G ram的vps

**Comment by 546669204** [comment]
讲道理不会 你查看vps 内存 cpu占用是 php 全吃掉了吗？

**Comment by aff2018** [comment]
cron的设置 定时访问URL 域名/index/index/test

用这种方式，昨晚8点到现在正常。看来，只好用这个了。

**Comment by 546669204** [comment]
讲道理是 使用cron 比较有危险 
因为是定时触发 不会检测是否还有任务在执行
好的。 现在稳定的就先用着
