### ISSUE TITLE
tg bot提醒的时候，希望把公司名也读取出来，怎么弄？

### ISSUE THREAD

**Issue by aff2018** [546669204/vps-inventory-monitoring#19]
在数据库里只有个”companyid”字段，发现公司名在另一个表里。
如何改这文件https://github.com/546669204/vps-inventory-monitoring/blob/master/app/index/model/Index.php
tg bot提醒的时候，获取到公司名称？

不好意思，又来麻烦大佬了。

**Comment by 546669204** [comment]
$company = Model("Company")->where(["id"=>$data["companyid"]])->find();
phpthink 的语法 

使用model  获取数据  $company 里面就是你要的数据

**Comment by aff2018** [comment]
> $company = Model("Company")->where(["id"=>$data["companyid"]])->find();
> phpthink 的语法
> 
> 使用model 获取数据 $company 里面就是你要的数据

代码水平太菜，求大佬直接修改一下这个文件吧。

**Comment by 546669204** [comment]
$company = Model("Company")->where(["id"=>$data["companyid"]])->find();
$company["name"] 就是 企业名字  你自己改字符串 连接 放到 哪里

**Comment by aff2018** [comment]
#相关代码：
public function test(){
        $list = $this->where(["status"=>1])->select();
        $r = [];
      	$log = Model('Log');
      	$index =  Model('Index');
        $user = Model("User");
        $request = request();
        $host = $request->domain();
        foreach ($list as $value){
            $curl = go_curl($value["vurl"],"get");
            if (config("app.testdebug")){
                file_put_contents(TEMP_PATH . "/debug.txt","------[START]------\n".date("Y-m-d h:i:s")."\n{$curl['RequestHeader']}\n\n{$curl['ResponseHeader']}\n{$curl['Body']}\n------[END]------",FILE_APPEND);
            }
            $str = $curl["Body"];
            $a = eval($value["vf"]);
            $r[] = "{$value['name']} --- " . (($a) ? 'true' : 'false');
            if ($a != $value["stock"]){
                $index->save(["stock"=>$a],["id"=>$value["id"]]);
                $log->data(["status"=>$a,"indexid"=>$value["id"]])->isUpdate(false)->save();
            }
            if ($value["stock"] == false && $a == true){
                $p = $user->where("find_in_set({$value['id']},subscribe)")->select();
                $title = "您关注的{$value['name']}有货啦。";
                $content = "您关注的{$value['name']}有货啦。\n快来大肆抢购呀。\n测评地址：$host/ceping/{$value['id']}\n购买地址：$host/buy/{$value['id']}";
                foreach ($p as $k => $v) {
                    if ($v["ftsckey"] != ""){
                        go_curl("https://sc.ftqq.com/{$v['ftsckey']}.send","post", ["text"=>$title,"desp"=>$content]);
                    }
                    if ($v["tgsckey"] != ""){
                        go_curl("https://cloud.hcaiyue.top/tgbot.php","post", ["method"=>"send","content"=>$content,"sckey"=>$v["tgsckey"]]);
                    }
                }
                if (config("app.tgchannelsckey") != ""){
                    go_curl("https://cloud.hcaiyue.top/tgbot.php","post", ["method"=>"send","content"=>$content,"sckey"=>config("app.tgchannelsckey")]);
                }
            }
        }
        return "<pre>" . join($r,"\n") . "\nOK" . "</pre>";
    }

#想放到这里：

$content = "您关注的$company["name"] {$value['name']}有货啦。\n优惠码：{$value['promo']}\n测评地址：$host/ceping/{$value['id']}\n购买地址：$host/buy/{$value['id']}";

#这句：$company = Model("Company")->where(["id"=>$data["companyid"]])->find();
放在什么位置？

**Comment by 546669204** [comment]
查询 放在使用之前

**Comment by aff2018** [comment]
public function test(){
$company = Model("Company")->where(["id"=>$data["companyid"]])->find();
$list = $this->where(["status"=>1])->select();
$r = [];

我放这里，出错了

**Comment by 546669204** [comment]
你要保证 你传入的 $data["companyid"] 这个 东西是否存在 ， 企业id 是 这个  $value["companyid"]

**Comment by aff2018** [comment]
失败，搞不像

**Comment by 546669204** [comment]
```
            }
            if ($value["stock"] == false && $a == true){
<-----
$itemCompany = Model("Company")->where(["id"=>$value["companyid"]])->find();
<-----
                $p = $user->where("find_in_set({$value['id']},subscribe)")->select();
                $title = "您关注的{$itemCompany["name"]}{$value['name']}有货啦。";
                $content = "您关注的{$value['name']}有货啦。\n快来大肆抢购呀。\n测评地址：$host/ceping/{$value['id']}\n购买地址：$host/buy/{$value['id']}";
                foreach ($p as $k => $v) {
                    if ($v["ftsckey"] != ""){
                        go_curl("https://sc.ftqq.com/{$v['ftsckey']}.send","post", ["text"=>$title,"desp"=>$content]);
                    }
                    if ($v["tgsckey"] != ""){
                        go_curl("https://cloud.hcaiyue.top/tgbot.php","post", ["method"=>"send","content"=>$content,"sckey"=>$v["tgsckey"]]);
                    }
                }
                if (config("app.tgchannelsckey") != ""){
                    go_curl("https://cloud.hcaiyue.top/tgbot.php","post", ["method"=>"send","content"=>$content,"sckey"=>config("app.tgchannelsckey")]);
                }
            }
```

**Comment by aff2018** [comment]
不好意思，又来麻烦你了，这回用php vpstest的方式，出现错误提示：
[InvalidArgumentException]                         
  property not exists:app\index\model\company
下面的代码
$itemCompany = Model("Company")->where(["id"=>$value["companyid"]])->find();
插入到下面这个文件里
https://github.com/546669204/vps-inventory-monitoring/blob/master/app/index/command/VpsTest.php
