### ISSUE TITLE
给“购买地址”文字加连接，在你的代码里应该怎么写？

### ISSUE THREAD

**Issue by aff2018** [546669204/vps-inventory-monitoring#21]
```
$title = "您关注的{$value['name']}有货啦。";
$content = "您关注的{$value['name']}有货啦。{$itemplace["name"]}\n{$itemCompany["name"]}\n{$value['frame']}|{$value['ram']}|{$value['disk']}|{$value['flow']}@{$value['bandwidth']}|{$value['route']}\n月付:{$value['monthly']}\n年付:{$value['yearly']}\n测评地址：$host/ceping/{$value['id']}\n购买地址：$host/buy/{$value['id']}";
```
 目前发送的效果是：
测评地址：http://域名/ceping/123
购买地址：http://域名/buy/123
要写成<a href="http://域名/ceping/123">测评地址</a>\
也就是给文字加连接，在你的代码里应该怎么写？
请示范一下。

另外有个小问题关于$host，得到的是http://域名/ceping/123。而不是https://，我的站已强制使用https
不知道是哪里有问题。
谢谢啦。

**Comment by 546669204** [comment]
1.支持markdown 的情况下可以使用 

```
[测评地址]($host/ceping/{$value['id']}) 
```
演示 [测评地址]($host/ceping/{$value['id']}) 
实现类似a标签的效果
   
2.
修改 vps-inventory-monitoring/app/index/config.php 下的 host

**Comment by aff2018** [comment]
[测评地址]($host/ceping/{$value['id']}) 
推送动tg时，直接就是：

 `[测评地址](网址/ceping/123)`

好像不行

**Comment by 546669204** [comment]
在 https://github.com/546669204/Telegram-Push-Bot/blob/master/bot.php
每行sendmessage($data); 之前加一行
```
$data["parse_mode"] = "Markdown"; // 值是Markdown或HTML 
```

**Comment by aff2018** [comment]
![D6E3E6B0-1166-4FDB-B09B-F7E5CDFAB028](https://user-images.githubusercontent.com/39473264/67556821-74271300-f746-11e9-8dfd-b68ac812c426.jpeg)
加了，就三个地方吧，结果，tg 没接收到推送

**Comment by 546669204** [comment]
你的引号有问题 不是半角的

**Comment by aff2018** [comment]
成功了，谢谢🙏。我是直接复制你的，竟然会变。大佬，强烈要求开起pp捐赠。
