### ISSUE TITLE
可以只特定ID检查是否有库存吗？

### ISSUE THREAD

**Issue by ttydy** [546669204/vps-inventory-monitoring#22]
要检查的加的有点多，整个循环下来要8分钟左右了，感觉慢了点。可以只设置循环检查特定ID吗？

**Comment by 546669204** [comment]
可以把不需要检测的禁用 status

**Comment by ttydy** [comment]
> 可以把不需要检测的禁用 status

你的意思是直接把 status 改为0？

**Comment by 546669204** [comment]
是的 只有1才会检测

**Comment by ttydy** [comment]
好的，感谢。我去试试。

**Comment by ttydy** [comment]
感谢，有效。

另再问一个问题，有这么个情况：有个网站的aff不能用链接的形式到达到指定商品。有没有什么办法可以先点击aff链接不跳转，再点正确的跳转链接。比如：要先点 https://www.aaa.com/aff，点这个的时候不跳转，点https://www.aaa.com/?id=15时跳转。（也就是说点https://www.aaa.com/?id=15时先接受https://www.aaa.com/aff的cookie）

**Comment by ttydy** [comment]
在不，上面的问题要怎么处理。不太懂这方面。

**Comment by 546669204** [comment]
你可以写一个网站  然后跳转到这个网址  xxxx/aaa.html
``` 
// 如 aaa.html
<html>
<iframe src="https://www.aaa.com/aff" style="display:none"/>
<iframe src="https://www.aaa.com/?id=15" style="width:100vw;height:100vh"/>
</html>
```

**Comment by ttydy** [comment]
大佬，我直接按你的代码新建了一个html页面，aff是有了，但是没调转到https://www.aaa.com/?id=15。是什么原因？

**Comment by 546669204** [comment]
代码发出来看看

**Comment by ttydy** [comment]
<html>
<iframe src="https://www.aaa.com/aff" style="display:none"/>
<iframe src="https://www.aaa.com/?id=15" style="width:100px;height:100px"/>
</html>

直接copy了你的建立了一个单独的页面。

**Comment by 546669204** [comment]
换成这样
```
<html>
<iframe src="https://www.aaa.com/aff" style="display:none"></iframe>
<iframe src="https://www.aaa.com/?id=15" style="width:100vw;height:100vh"></iframe>
</html>
```

**Comment by ttydy** [comment]
会跳转了，但是，地址栏不会变。

**Comment by 546669204** [comment]
是呀 不会跳转 
```
<html>
<iframe src="https://www.aaa.com/aff" style="display:none"></iframe>
页面跳转中 5.
<script>
setTimeout(function(){
location.href = "https://www.aaa.com/?id=15"
},5000)
</script>
</html>
```

**Comment by ttydy** [comment]
太感谢了，有用了。谢谢。
