### ISSUE TITLE
请问一下有推送到QQ群的吗？

### ISSUE THREAD

**Issue by ttydy** [546669204/vps-inventory-monitoring#23]
大佬，问一下，有推送到QQ群的程序推荐吗？

**Comment by 546669204** [comment]
可以使用酷Q实现 
具体实现可以参考 https://github.com/richardchien/coolq-http-api

**Comment by ttydy** [comment]
好的，谢谢。另外我想问一下下面链接有没有好的方法判断有货还是没有货。（卡片式的）

https://clientarea.gigsgigscloud.com/index.php?/cart/cloudlet-v-lax/&step=0

**Comment by 546669204** [comment]
暂时没有特别好的办法

**Comment by ttydy** [comment]
[是说的这个id吗？](https://s2.ax1x.com/2020/02/25/3YsOBV.png)

vurl 里面不可以直接写下面这种吧。
curl -F "id=118" -X POST https://clientarea.gigsgigscloud.com/?cmd=cart&cat_id=24

**Comment by 546669204** [comment]
不能 这个网站会检测cookie 
目前没有太完美的解决办法

**Comment by ttydy** [comment]
这家改过来了，现在可以检测到了。

https://manage.hostdare.com/cart.php?a=add&pid=74  无货
https://manage.hostdare.com/cart.php?a=add&pid=75  有货

我只留下面的代码，有货的老是检测不出来。能帮忙看一下是什么问题吗？

if(strpos($str,"Out of Stock")!==false){
    return false;
}
return true;

**Comment by 546669204** [comment]
查了一下 这个家 挂了 CloudFlare 的cdn 防ddos的 cf 有时候会做机器人检测 然后 可能被限制了。

**Comment by ttydy** [comment]
谢谢，hostdare家的我发tk看能不能解决。

另外，如果下面这个网站打不开的话就会乱报，有变法解决吗？
https://clientarea.gigsgigscloud.com/index.php?/cart/cloudlet-v-lax/&step=0

这检验条件：
if ($curl["Code"] != 200){
    return false;
}
if (strpos($str,"Order")==false){
    return $value["stock"];
}
if (strpos($str,"CLOUDLET LAX-V2")==false){ //不知道是不是和这个有关系。
    return false; 
}
return true;

**Comment by ttydy** [comment]
> 可以使用酷Q实现
> 具体实现可以参考 https://github.com/richardchien/coolq-http-api

昨天安装了这个。像下面的用变量不发送，只有一个变量的时候就可以。是不是不能用”|“的问题（\n\n 好像也不能有。）？这种要怎么写。
$content = "补货了！\n\n{$value['companyname']} | {$value['name']} | {$value['frame']}“
http://192.168.1.123:5700/send_private_msg?user_id=123456&message=$content

**Comment by ttydy** [comment]
酷Q 这个问题知道原因了。
