### ISSUE TITLE
误报问题。

### ISSUE THREAD

**Issue by ttydy** [546669204/vps-inventory-monitoring#24]
大佬，问一下。商家网站要是被打了，就会误报。有什么办法解决吗？

参数都是类似于下面的来的。
if ($curl["Code"] != 200){ //首先判断状态码
    return false;
}
if (strpos($str,"MineCloud")==false){ //检测是否正常打开有无公司名字之类关键词
    return $value["stock"]; //返回原库存状态
}
if (strpos($str,"缺货中")!==false){ //检测是否含有缺货关键词
    return false; 
}
return true;

**Comment by 546669204** [comment]
```
if ($curl["Code"] != 200){ //首先判断状态码
return false;
}
《----- start
// 使用这个一块来判断 网站是否被打了 这里是判断如果不能找到mineCloud 那就不继续执行 你可以把mineCloud 换成正常情况下出现 被打不会出现的关键词
if (strpos($str,"MineCloud")==false){ //检测是否正常打开有无公司名字之类关键词
return $value["stock"]; //返回原库存状态
}
《------ end
if (strpos($str,"缺货中")!==false){ //检测是否含有缺货关键词
return false;
}
return true;
```

**Comment by ttydy** [comment]
我是这样做的。但是被打还是误报。

if ($curl["Code"] != 200){ //首先判断状态码
    return false;
}

// Order以前是公司名，被打了还是报错。
if (strpos($str,"Order")==false){ //检测是否正常打开有无公司名字之类关键词
    return $value["stock"]; //返回原库存状态
}
《----- start
//是和这一条有关系吗？
if(strpos($str,"CLOUDLET V2")==false){
    return false;
}
《------ end
return true;

**Comment by 546669204** [comment]
是不是 被打的时候 网页里面还是有order的  

如果上面返回了 下面是不会执行的

**Comment by ttydy** [comment]
应该是有缓存。改成商品名好像也会。（前面一直在等这个问题出现。）
