### ISSUE TITLE
链接可以带参数吗？

### ISSUE THREAD

**Issue by ttydy** [546669204/vps-inventory-monitoring#25]
链接可以带参数吗？比如带一参数显示商家的全部产品。

**Comment by 546669204** [comment]
比如 `http://www.baidu.com/?q=1`
这样就是一个带参数的链接

**Comment by ttydy** [comment]
> 比如 `http://www.baidu.com/?q=1`
> 这样就是一个带参数的链接

https://vps.aaa.com/?placeid=1
https://vps.aaa.com/?company=Bandwagonhost
我改成上面这样，但好像不超作用。请问要怎么改？

**Comment by 546669204** [comment]
理论上是支持的  发下你是怎么配置的？

**Comment by ttydy** [comment]
> 理论上是支持的 发下你是怎么配置的？

具体是哪个地方的配置？vps.aaa.com 这是我搭建的。

**Comment by 546669204** [comment]
表 xm_index  
字段 ceping // 测评地址  
字段 buy // 购买地址 

换这几个字段

**Comment by ttydy** [comment]
抱歉，不是特别懂你什么意思。

**Comment by ttydy** [comment]
我用类似于下面这种也没有用。
https://vps.aaa.com/?buy=gigsgigscloud

**Comment by 546669204** [comment]
你的意思是通过参数筛选网站里面的 服务 比如 只显示 dmit家的产品？ 

这个功能目前没有
