### ISSUE TITLE
关于tgbot推送

### ISSUE THREAD

**Issue by likecreep** [546669204/vps-inventory-monitoring#31]
搭建后，添加webhook返回webhook设置成功。但是私聊tgbot并不会回复sckey。请问是现在这个方法失效了吗？

**Comment by 546669204** [comment]
bot.php 里面的 `[token]` 有换成自己的机器人token吗？

**Comment by likecreep** [comment]
> bot.php 里面的 `[token]` 有换成自己的机器人token吗？
> 
> 

你好，有更换的，访问telegram的api也返回设置成功了，但是发送消息并没有收到bot的任何回复，所以一直没有获取到sckey

**Comment by 546669204** [comment]
需要发送指定消息 `/start` 使用的是这一份bot.php吗 
https://github.com/546669204/Telegram-Push-Bot/blob/master/bot.php

**Comment by likecreep** [comment]
> 需要发送指定消息 `/start` 使用的是这一份bot.php吗 
> 
> https://github.com/546669204/Telegram-Push-Bot/blob/master/bot.php

是的，是这份文件并且是发送的/start，也开启了https。

**Comment by 546669204** [comment]
刚刚试了一下没有问题。 
是不是webhook没有设置好
https://api.telegram.org/bot这里写机器人token/setWebhook?url=这里写你的机器人地址

还有你的机器人是不是封了海外的请求访问？

**Comment by likecreep** [comment]
> 刚刚试了一下没有问题。 
> 
> 是不是webhook没有设置好
> 
> https://api.telegram.org/bot这里写机器人token/setWebhook?url=这里写你的机器人地址
> 
> 
> 
> 还有你的机器人是不是封了海外的请求访问？

前面都没问题。请问怎么判断机器人是否封了海外请求？

**Comment by 546669204** [comment]
你的服务器是国内的吗？可以换个海外的试试。

**Comment by likecreep** [comment]
找到出错原因了，Wrong response from the webhook: 405 Not Allowed  。请问这个有办法解决吗？

**Comment by 546669204** [comment]
> 找到出错原因了，Wrong response from the webhook: 405 Not Allowed 。请问这个有办法解决吗？

https://core.telegram.org/bots/webhooks#testing-your-bot-with-updates
可以尝试自己模拟一下发送请求。看看那一步有问题。

**Comment by likecreep** [comment]
啊搞定了。是我一开始把服务器设置成静态网页了 打扰了。
