### ISSUE TITLE
大佬好，看一下我写的首页

### ISSUE THREAD

**Issue by starsxxm** [546669204/vps-inventory-monitoring#35]
![Snipaste_2023-12-10_01-10-36](https://github.com/546669204/vps-inventory-monitoring/assets/81069939/816ff0ad-ddb5-48bf-89f2-98148f9e7f3c)

刚学会写点简单的代码，写了一个首页
![1B573175](https://github.com/546669204/vps-inventory-monitoring/assets/81069939/1f18a4ef-c518-4aa6-93fc-24baea321288)

**Comment by 546669204** [comment]
👍 非常好。💯
