### ISSUE TITLE
添加监控404

### ISSUE THREAD

**Issue by Sooele** [546669204/vps-inventory-monitoring#4]
宝塔面板，搭建完成有，添加服务器监控时候跳转过去是404。。

stock.sooele.com

**Comment by 546669204** [comment]
设置一下url rewrite 
参考 [ThinkPHP URL重写](https://www.kancloud.cn/manual/thinkphp5/177576)

**Comment by Sooele** [comment]
是直接添加上去？

**Comment by 546669204** [comment]
是的设置文件 
Apache  设置 更目录下的.htaccess 
IIS 设置 web.Config
Niginx 设置 Nginx.conf

**Comment by Sooele** [comment]
location / { /******/ 
   if (!-e $request_filename) {
   rewrite  ^(.*)$  /index.php?s=/$1  last;
   break;
    }
 }

指的是运行目录吗

**Comment by 546669204** [comment]
是的你放public下

**Comment by Sooele** [comment]
添加是添加在
server{
}内

还是外

**Comment by 546669204** [comment]
内

**Comment by Sooele** [comment]
location / { //www/wwwroot/stock.sooele.com/public/ 
   if (!-e $request_filename) {
   rewrite  ^(.*)$  /index.php?s=/$1  last;
   break;
    }
 }

不错是否有错！

**Comment by 546669204** [comment]
按理说没有问题。

**Comment by Sooele** [comment]
NG添加出现错误。。
版本1.12  宝塔的！！

**Comment by 546669204** [comment]
晚一点我联系你 我帮你看下。

**Comment by Sooele** [comment]
好。谢了！

**Comment by 546669204** [comment]
在吗 加一下我qq 546669204 给我提供一下控制面板

**Comment by Sooele** [comment]
好。你可以删记录了
