### ISSUE TITLE
主键冲突？？

### ISSUE THREAD

**Issue by sgwyhwt** [546669204/vps-inventory-monitoring#5]
运行`php think VpsTest`
出现`SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '220' for key 'PRIMARY' `

**Comment by 546669204** [comment]
您好可以提供面板让我检查下吗。

**Comment by sgwyhwt** [comment]
是网站的地址？
第一次运行的时候出现这样的错误，后面再运行一次就没事了，可以用supervisor来监控的

**Comment by 546669204** [comment]
数据库分享一下我重建你的生产环境来测试

**Comment by sgwyhwt** [comment]
大佬有TG或者什么交流群么？
数据库在这里上传不了吧

**Comment by 546669204** [comment]
https://t.me/a546669204 看看能不能搜到
