### ISSUE TITLE
请教下，首页默认显示10条信息，如何改成默认现在20条？

### ISSUE THREAD

**Issue by guonning** [546669204/vps-inventory-monitoring#7]
谢谢啊

**Comment by 546669204** [comment]
修改 app/index/view/index.html里面的data-page-list 10改成20

**Comment by guonning** [comment]
非常感谢

**Comment by guonning** [comment]
data-page-list="[10, 25, 50, 100, ALL]"
改成了 data-page-list="[20, 25, 50, 100, ALL]"
还是显示10条，只是没有页面的下拉框了

**Comment by 546669204** [comment]
你的数据有超过十条吗。

**Comment by guonning** [comment]
20条，没问题的。
你可以试下。

**Comment by 546669204** [comment]
不好意思。刚刚试了一下。需要增加一条data-page-size=“20”在page-list 上面或者下面

**Comment by guonning** [comment]
data-page-list="[20, 25, 50, 100, ALL]"
data-page-size=“20”
合适吗？
我试了下，加到上面 、下面，都显示 没有找到匹配的记录。

**Comment by 546669204** [comment]
那个引号换成英文的引号

**Comment by guonning** [comment]
非常感谢！！！
