### ISSUE TITLE
php think VpsTest，提示数据库密码问题

### ISSUE THREAD

**Issue by hxf3591126** [546669204/vps-inventory-monitoring#9]
问题1：
运行   php think VpsTest   这个

[PDOException]                                                                         
  SQLSTATE[HY000] [1045] Access denied for user 'root'@'localhost' (using password: NO) 

我在这个地方已经配置了用户名密码了的： vps-inventory-monitoring/app/database.example.php

问题2：
app/index/config.php
已经在我的tel群里加入了机器人，但是好像得不到：在频道发送 /start 获取sckey

求解

**Comment by 546669204** [comment]
问题1 需要把vps-inventory-monitoring/app/database.example.php 重命名掉 vps-inventory-monitoring/app/database.php
问题2给机器人设置权限了吗 用我的机器人接口还是自己的看看配置有没有问题

**Comment by hxf3591126** [comment]
1.
vps-inventory-monitoring/app/database.php
改名后，打开网站就出来了。

2.
 php think VpsTest这个需要运行吗？做什么用？

3.
后台怎么管理。里面546669204这个帐号，密码是什么？
另外自己添加的帐号，没法添加监控，说权限不足

**Comment by hxf3591126** [comment]
问题3，解决了，直接贴了个密码给这个原始帐号，也登录上去了。

现在的问题是怎么管理这些已发监控：只能增加监控，不能修改或删除？

**Comment by 546669204** [comment]
php think VpsTest 需要在ssh里面运行或者使用cron定时检测


数据里里面修改删除数据

**Comment by hxf3591126** [comment]
需要在ssh里面运行，太麻烦
使用cron定时检测，怎么搞？

直接数据库里修改删除数据啊？这个有点夸张

**Comment by 546669204** [comment]
ssh 的方式稳定点  cron的话设置 定时访问URL  域名/index/index/test

**Comment by 546669204** [comment]
一般修改删除不会很多的

**Comment by hxf3591126** [comment]
谢谢大佬耐心解答。
tele频道和群是两个概念吗？tele群里不行吗？
// 邀请https://t.me/VpsStockBot进入频道 设置为管理员 然后在频道发送 /start 获取sckey 填入
tele群group和channel，都试过。没成功。

**Comment by 546669204** [comment]
是的 群和频道不一样 频道不能随意发言

**Comment by hxf3591126** [comment]
加vpsstockbot入频道时，提示“could not add use.please try again later”

**Comment by hxf3591126** [comment]
加别的人时，正常能加入。而这个机器人加不进去，什么情况？

**Comment by 546669204** [comment]
J就是设置机器人为管理员 然后给对应的权限

**Comment by hxf3591126** [comment]
可以了，直接添加管理员
谢谢

**Comment by hxf3591126** [comment]
/start
在频道里发送这个，机器人没给我sckey

**Comment by 546669204** [comment]
有设置你的机器人token吗

**Comment by ttydy** [comment]
> 有设置你的机器人token吗

可以设置自己机器人的token？怎么设置？自己的机器人要用什么项目？
